Feature/star 359
EscolaLMS/Admin pull request #367
Opened 2022-03-04 11:25 UTC by tomekgubernat

2022-03-04 11:44 UTC, victazzz approved these changes

2022-03-04 11:53 UTC, victazzz requested changes

2022-03-04 11:53 UTC, victazzz commented on src/components/UserRoleSelect/index.tsx
> +          <Select.Option key={role.id} value={role.name}>
value={role.id}

2022-03-04 14:05 UTC, victazzz commented on src/components/UserRoleSelect/index.tsx
> +          <Select.Option key={role.id} value={role.name}>
it has to be role.name

2022-03-30 11:27 UTC, qunabu commented
@victazzz @tomekgubernat merge or close

2022-03-30 13:50 UTC, merged