Feature/vouchers
EscolaLMS/Admin pull request #405
Opened 2022-03-21 15:31 UTC by victazzz

2022-03-22 19:01 UTC, qunabu requested changes

2022-03-22 19:01 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +import { request } from 'umi';
use requests from export https://escolalms.github.io/ts-models/modules/EscolaLms.Vouchers.Http.Requests.html

2022-03-22 19:01 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +import { request } from 'umi';
Add this defs to all requests

2022-03-23 17:56 UTC, qunabu requested changes

2022-03-23 17:56 UTC, qunabu commented on src/components/ProductsSelect/index.tsx
> +export default UserSelect;
```suggestion
export default ProductsSelect;
```

2022-03-23 17:56 UTC, qunabu commented on src/pages/Vouchers/form.tsx
> +  const [data, setData] = useState<Partial<EscolaLms.Vouchers.Models.Coupon>>();
up up

2022-03-23 17:56 UTC, qunabu commented on src/pages/Vouchers/index.tsx
> +  const [loading, setLoading] = useState(false);
```suggestion
  const [loading, setLoading] = useState<boolean>(false);
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +  return request<API.DefaultMetaResponse<EscolaLms.Vouchers.Http.Requests.ListCouponsRequest>>(
```suggestion
export async function vouchers(params?: API.PageParams & EscolaLms.Vouchers.Http.Requests.ListCouponsRequest, options?: RequestOptionsInit) {
  return request<API.DefaultMetaResponse<EscolaLms.Vouchers.Models.Coupon>>(
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +export async function createVoucher(body?: Record<string, any>, options?: Record<string, any>) {
```suggestion
export async function createVoucher(body?: CreateCouponRequest, options?: RequestOptionsInit) {
```



in import parts 
```ts 
import type { RequestOptionsInit } from 'umi-request';
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +export async function getVoucher(id: number, options?: Record<string, any>) {
```suggestion
export async function getVoucher(id: number, options?: RequestOptionsInit) {
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +  options?: Record<string, any>,
```suggestion
  body?: EscolaLms.Vouchers.Http.Requests. UpdateCouponRequest,
  options?: RequestOptionsInit,
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/vouchers.ts
> +export async function deleteVoucher(id: number, options?: Record<string, any>) {
```suggestion
export async function deleteVoucher(id: number, options?: RequestOptionsInit) {
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/webinars.ts
> +export async function createWebinar(body?: Partial<API.Webinar>, options?: Record<string, any>) {
```suggestion
export async function createWebinar(body?: Partial<API.Webinar>, options?: RequestOptionsInit) {
```

2022-03-23 17:56 UTC, qunabu commented on src/services/escola-lms/webinars.ts
>  export async function deleteWebinar(id: number, options?: Record<string, any>) {
```suggestion
export async function deleteWebinar(id: number, options?: RequestOptionsInit) {
```

2022-03-23 19:46 UTC, victazzz commented on src/pages/Vouchers/form.tsx
> +  const [data, setData] = useState<Partial<EscolaLms.Vouchers.Models.Coupon>>();
the id is missing from these types and I don't know if it is better to extend this type & {id: or use this type with models?

2022-03-24 20:06 UTC, qunabu approved these changes

2022-03-24 20:06 UTC, merged